-- Smart Quote: richer AI output + private customer attachment storage.

alter table public.quote_requests
  add column if not exists project_line text,
  add column if not exists ai_project_description text,
  add column if not exists owner_notes text;

comment on column public.quote_requests.project_line is
  'Short internal project label generated from the customer intake.';

comment on column public.quote_requests.ai_project_description is
  'Customer-facing AI project description generated from the quote intake.';

comment on column public.quote_requests.owner_notes is
  'Private owner/estimator notes generated by AI for follow-up.';

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'quote-attachments',
  'quote-attachments',
  false,
  26214400,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'image/heif',
    'application/pdf',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Staff select quote attachments" on storage.objects;
create policy "Staff select quote attachments"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'quote-attachments'
    and exists (
      select 1 from public.staff_profiles sp
      where sp.id = (select auth.uid())
    )
  );
